/**
 * content-bake.ts — Vite plugin that bakes static content into the build.
 *
 * Reads content/posts/*.md at dev-start and build-start, renders each
 * to HTML (via marked), and generates src/content-data.ts with all
 * baked post metadata + HTML.
 *
 * Content is always baked (dev and prod). The SPA never fetches
 * from an API at runtime — it reads bakedPosts directly.
 *
 * Uses gray-matter + marked directly (not @anomalous/blog-shared) because
 * vite.config.ts plugins run in Node.js and workspace .ts source exports
 * aren't resolvable via ESM before their own build step.
 */

import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import type { Plugin } from "vite";

const __dirname = dirname(fileURLToPath(import.meta.url));
const POSTS_DIR = join(__dirname, "content", "posts");

async function bakeContent(): Promise<string> {
  const { default: matter } = await import("gray-matter");
  const { marked: marked_ } = await import("marked");
  const marked = marked_ as unknown as { parse: (md: string) => Promise<string> };

  if (!existsSync(POSTS_DIR)) {
    console.warn(`[blog-content-bake] No posts directory at ${POSTS_DIR}`);
    return generateModule([]);
  }

  const files = readdirSync(POSTS_DIR).filter((f) => f.endsWith(".md"));
  console.log(`[blog-content-bake] Baking ${files.length} posts...`);

  const posts: Array<{
    slug: string; title: string; date: string; description: string; tags: string[]; content: string;
  }> = [];

  for (const file of files) {
    const slug = file.replace(/\.md$/, "");
    const raw = readFileSync(join(POSTS_DIR, file), "utf-8");
    const { data, content } = matter(raw);
    const html = await marked.parse(content);

    posts.push({
      slug,
      title: (data.title as string) ?? slug,
      date: (data.date as string) ?? new Date().toISOString(),
      description: (data.description as string) ?? "",
      tags: Array.isArray(data.tags) ? (data.tags as string[]) : [],
      content: html,
    });

    console.log(`[blog-content-bake]   ${slug}`);
  }

  posts.sort((a, b) => String(b.date).localeCompare(String(a.date)));
  return generateModule(posts);
}

function generateModule(posts: Array<{
  slug: string; title: string; date: string; description: string; tags: string[]; content: string;
}>): string {
  const json = JSON.stringify(posts);
  return `// Auto-generated by blog-content-bake Vite plugin.
// Contains all published blog posts rendered to HTML.
// Re-generated on dev-start and build-start.

export interface BakedPost {
  slug: string;
  title: string;
  date: string;
  description: string;
  tags: string[];
  content: string; // rendered HTML
}

export const bakedPosts: BakedPost[] = ${json};
`;
}

export function contentBakePlugin(): Plugin {
  return {
    name: "blog-content-bake",
    enforce: "pre",

    async buildStart() {
      const outPath = join(__dirname, "src", "content-data.ts");
      mkdirSync(dirname(outPath), { recursive: true });

      try {
        const code = await bakeContent();
        writeFileSync(outPath, code, "utf-8");
      } catch (err) {
        console.error(`[blog-content-bake] Bake failed, using empty:`, err);
        writeFileSync(outPath, generateModule([]), "utf-8");
      }
    },

    configureServer() {
      // Also bake on dev start so the SPA has content immediately.
      // buildStart fires during dev's internal bundling too, but the
      // timing varies. configureServer gives a guaranteed first bake.
      const outPath = join(__dirname, "src", "content-data.ts");
      mkdirSync(dirname(outPath), { recursive: true });
      bakeContent()
        .then((code) => writeFileSync(outPath, code, "utf-8"))
        .catch((err) => {
          console.error(`[blog-content-bake] Dev bake failed:`, err);
          writeFileSync(outPath, generateModule([]), "utf-8");
        });
    },
  };
}
