// Generated by ano-server — do not edit.
// Imports your vite config and sets the correct base for dev vs serve.

import userConfig from "../vite.config.js";

const devBase = "/api/v1/apps/blog/dev/s";
const serveBase = "/api/v1/apps/blog/s";

// Always produce a function so both object and function-form configs work.
// Calls the user's config (if it's a function) and overrides base.
export default (env) => {
  const resolved = typeof userConfig === "function" ? userConfig(env) : userConfig;
  return {
    ...resolved,
    base: process.env.ANO_MODE === "dev" ? devBase : serveBase,
  };
};
