// Generated by ano-server — do not edit.
// Imports your vite config and sets the correct base for dev vs serve.
// Set ANO_VITE_CONFIG to override the default config filename at runtime.

import { fileURLToPath } from "node:url";
import path from "node:path";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const devBase = "/api/v1/apps/blog/dev/s";
const serveBase = "/api/v1/apps/blog/s";

// ANO_VITE_CONFIG env var overrides the default vite config file.
// Value is relative to the app root (e.g. "vite.mcp.config.ts").
const configFile = process.env.ANO_VITE_CONFIG || "vite.config.ts";
const configPath = path.join(__dirname, "..", configFile);

// Use a dynamic import so the override is resolved at spawn time.
// Async config functions are supported natively by Vite.
export default async (env) => {
  const mod = await import(configPath);
  const userConfig = mod.default;
  if (!userConfig) throw new Error("vite config at " + configPath + " has no default export");
  const resolved = typeof userConfig === "function" ? await userConfig(env) : userConfig;
  return {
    ...resolved,
    base: process.env.ANO_MODE === "dev" ? devBase : serveBase,
  };
};
